package com.esde.emulatormanager.data.parser

import com.esde.emulatormanager.data.model.EmulatorCommand
import com.esde.emulatormanager.data.model.EmulatorRule
import com.esde.emulatormanager.data.model.GameSystem
import java.io.StringWriter
import javax.xml.parsers.DocumentBuilderFactory
import javax.xml.transform.OutputKeys
import javax.xml.transform.TransformerFactory
import javax.xml.transform.dom.DOMSource
import javax.xml.transform.stream.StreamResult

/**
 * Writer for ES-DE configuration files (custom es_systems.xml and es_find_rules.xml)
 */
class EsdeConfigWriter {

    /**
     * Generate es_systems.xml content for custom systems
     */
    fun generateSystemsXml(systems: List<GameSystem>): String {
        val docBuilder = DocumentBuilderFactory.newInstance().newDocumentBuilder()
        val doc = docBuilder.newDocument()

        // Create root element first
        val root = doc.createElement("systemList")
        doc.appendChild(root)

        // Add each system
        // ES-DE requires elements in specific order: name, fullname, path, extension, command(s), platform, theme
        for (system in systems) {
            val systemElement = doc.createElement("system")

            addElement(doc, systemElement, "name", system.name)
            addElement(doc, systemElement, "fullname", system.fullName)
            addElement(doc, systemElement, "path", system.path)
            addElement(doc, systemElement, "extension", system.extensions)

            // Add commands - each with a label for alternative emulator selection
            for ((index, command) in system.commands.withIndex()) {
                val cmdElement = doc.createElement("command")
                val labelValue = command.label ?: if (index == 0) "Default" else "Alternative ${index}"
                cmdElement.setAttribute("label", labelValue)
                cmdElement.textContent = command.command
                systemElement.appendChild(cmdElement)
            }

            addElement(doc, systemElement, "platform", system.platform)
            addElement(doc, systemElement, "theme", system.theme)

            root.appendChild(systemElement)
        }

        return transformToString(doc, " This is the ES-DE game systems configuration file for Android - Generated by EMAN ")
    }

    /**
     * Generate es_find_rules.xml content for emulator rules
     */
    fun generateFindRulesXml(rules: List<EmulatorRule>): String {
        val docBuilder = DocumentBuilderFactory.newInstance().newDocumentBuilder()
        val doc = docBuilder.newDocument()

        // Create root element
        val root = doc.createElement("ruleList")
        doc.appendChild(root)

        // Add each emulator rule
        for (rule in rules) {
            val emulatorElement = doc.createElement("emulator")
            emulatorElement.setAttribute("name", rule.name)

            val ruleElement = doc.createElement("rule")
            ruleElement.setAttribute("type", "androidpackage")

            for (entry in rule.entries) {
                val entryElement = doc.createElement("entry")
                entryElement.textContent = entry
                ruleElement.appendChild(entryElement)
            }

            emulatorElement.appendChild(ruleElement)
            root.appendChild(emulatorElement)
        }

        return transformToString(doc, " This is the ES-DE find rules configuration file for Android - Generated by EMAN ")
    }

    private fun addElement(doc: org.w3c.dom.Document, parent: org.w3c.dom.Element, name: String, value: String) {
        val element = doc.createElement(name)
        element.textContent = value
        parent.appendChild(element)
    }

    private fun transformToString(doc: org.w3c.dom.Document, commentText: String): String {
        val transformer = TransformerFactory.newInstance().newTransformer()
        transformer.setOutputProperty(OutputKeys.INDENT, "yes")
        transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "4")
        transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "yes")

        val writer = StringWriter()
        transformer.transform(DOMSource(doc), StreamResult(writer))

        val xmlContent = writer.toString().trim()
        
        // Construct final string with XML declaration and comment on separate lines
        return buildString {
            append("<?xml version=\"1.0\"?>\n")
            append("<!--$commentText-->\n")
            append(xmlContent)
            append("\n") // Ensure trailing newline
        }
    }
}
